module.exports = {
  USERVIEW: 'USERVIEW',
  USERREVIEW: 'USERREVIEW',
  USERADD: 'USERADD',
  USEREDIT: 'USEREDIT',
  USERDELETE: 'USERDELETE',
  CHGPERMISSIONUSER: 'CHGPERMISSIONUSER',

  CATEGORYVIEW: 'CATEGORYVIEW',
  CATEGORYREVIEW: 'CATEGORYREVIEW',
  CATEGORYADD: 'CATEGORYADD',
  CATEGORYEDIT: 'CATEGORYEDIT',
  CATEGORYDELETE: 'CATEGORYDELETE',

  PERMISSIONSVIEW: 'PERMISSIONSVIEW',
  PERMISSIONSREVIEW: 'PERMISSIONSREVIEW',
  PERMISSIONSADD: 'PERMISSIONSADD',
  PERMISSIONSEDIT: 'PERMISSIONSEDIT',
  PERMISSIONSDELETE: 'PERMISSIONSDELETE',

  VIDEOVIEW: 'VIDEOVIEW',
  VIDEOREVIEW: 'VIDEOREVIEW',
  VIDEOADD: 'VIDEOADD',
  VIDEOEDIT: 'VIDEOEDIT',
  VIDEODELETE: 'VIDEODELETE',

  BLOGVIEWALL: 'BLOGVIEWALL',
  BLOGVIEWPERSONAL: 'BLOGVIEWPERSONAL',
  BLOGADD: 'BLOGADD',
  BLOGEDIT: 'BLOGEDIT',
  BLOGDELETE: 'BLOGDELETE',
  BLOGREVIEW: 'BLOGREVIEW',
  BLOGNOTE: 'BLOGNOTE',

  PARTNERVIEW: 'PARTNERVIEW',
  PARTNERREVIEW: 'PARTNERREVIEW',
  PARTNERADD: 'PARTNERADD',
  PARTNEREDIT: 'PARTNEREDIT',
  PARTNERDELETE: 'PARTNERDELETE',

  BANNERVIEW: 'BANNERVIEW',
  BANNERREVIEW: 'BANNERREVIEW',
  BANNERADD: 'BANNERADD',
  BANNEREDIT: 'BANNEREDIT',
  BANNERDELETE: 'BANNERDELETE',

  SLIDEVIEW: 'SLIDEVIEW',
  SLIDEREVIEW: 'SLIDEREVIEW',
  SLIDEADD: 'SLIDEADD',
  SLIDEEDIT: 'SLIDEEDIT',
  SLIDEDELETE: 'SLIDEDELETE',

  ADVERTISEVIEW: 'ADVERTISEVIEW',
  ADVERTISEREVIEW: 'ADVERTISEREVIEW',
  ADVERTISEADD: 'ADVERTISEADD',
  ADVERTISEEDIT: 'ADVERTISEEDIT',
  ADVERTISEDELETE: 'ADVERTISEDELETE',

  COLLECTIONVIEW: 'COLLECTIONVIEW',
  COLLECTIONREVIEW: 'COLLECTIONREVIEW',
  COLLECTIONADD: 'COLLECTIONADD',
  COLLECTIONEDIT: 'COLLECTIONEDIT',
  COLLECTIONDELETE: 'COLLECTIONDELETE',

  HOMEMANAGERVIEW: 'HOMEMANAGERVIEW',
  HOMEMANAGERADDBLOG: 'HOMEMANAGERADDBLOG',

  CATEGORYLAYOUTVIEW: 'CATEGORYLAYOUTVIEW',
  CATEGORYLAYOUTREVIEW: 'CATEGORYLAYOUTREVIEW',
  CATEGORYLAYOUTADD: 'CATEGORYLAYOUTADD',
  CATEGORYLAYOUTEDIT: 'CATEGORYLAYOUTEDIT',
  CATEGORYLAYOUTDELETE: 'CATEGORYLAYOUTDELETE',

  CATEGORYPOSTLAYOUTVIEW: 'CATEGORYPOSTLAYOUTVIEW',
  CATEGORYPOSTLAYOUTREVIEW: 'CATEGORYPOSTLAYOUTREVIEW',
  CATEGORYPOSTLAYOUTADD: 'CATEGORYPOSTLAYOUTADD',
  CATEGORYPOSTLAYOUTEDIT: 'CATEGORYPOSTLAYOUTEDIT',
  CATEGORYPOSTLAYOUTDELETE: 'CATEGORYPOSTLAYOUTDELETE'
}
